=== domchenko/OldCards/resources/oldcards.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  xmlns:authorspace="http://www.example.net/test"> 

<xs:import schemaLocation="authorspace.xsd" namespace="http://www.example.net/test"/>
    
<xs:simpleType name="str">
   <xs:restriction base="xs:string">
     <xs:minLength value="1"/>
     <xs:whiteSpace value="collapse"/>
   </xs:restriction>
</xs:simpleType>


<!-- Elements declaration -->
<xs:element name="oldcard" type="oldcardType">
  <xs:annotation>
    <xs:documentation xml:lang="en">An old card</xs:documentation>
  </xs:annotation>
</xs:element>
<xs:element name="theme" type="str">
  <xs:annotation>
    <xs:documentation xml:lang="en">A short description, name of the picture, etc.</xs:documentation>
  </xs:annotation>
</xs:element>
<xs:element name="type" type="cardtypeType">
  <xs:annotation>
    <xs:documentation xml:lang="en">A type of the card</xs:documentation>
  </xs:annotation>
</xs:element>
<xs:element name="country" type="str">
  <xs:annotation>
    <xs:documentation xml:lang="en">A country of origin</xs:documentation>
  </xs:annotation>
</xs:element>
<xs:element name="year" type="yearType">
  <xs:annotation>
    <xs:documentation xml:lang="en">A year of publishing</xs:documentation>
  </xs:annotation>
</xs:element>
<xs:element name="authors" type="authorsType">
  <xs:annotation>
    <xs:documentation xml:lang="en">The authors of the card</xs:documentation>
  </xs:annotation>
</xs:element>
<xs:element name="author" type="authorspace:authorType">
  <xs:annotation>
    <xs:documentation xml:lang="en">An author details</xs:documentation>
  </xs:annotation>
</xs:element>
<xs:element name="valuable">
  <xs:simpleType>
    <xs:annotation>
      <xs:documentation xml:lang="en">A valuable of the card</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Historical"/>
      <xs:enumeration value="Thematic"/>
      <xs:enumeration value="Collection"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>


<xs:element name="oldcards">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="oldcard" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:complexType name="oldcardType">    
  <xs:sequence>
    <xs:element ref="theme"/>
    <xs:element ref="type"/>
    <xs:element ref="country"/>
    <xs:element ref="year"/>
    <xs:element ref="authors" minOccurs="0"/>
    <xs:element ref="valuable"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:ID" use="required"/>
</xs:complexType>

<xs:simpleType name="yearType">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="1600"/>
    <xs:maxInclusive value="2016"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="cardtypevalueType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Simple"/>
    <xs:enumeration value="Congratulatory"/>
    <xs:enumeration value="Promotional"/>
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="cardtypeType"> 
  <xs:simpleContent>
    <xs:extension base="cardtypevalueType">
      <xs:attribute name="isSent">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="yes|no"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:extension>
  </xs:simpleContent>
</xs:complexType>

<xs:complexType name="authorsType">    
  <xs:sequence>
    <xs:element ref="author" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

</xs:schema>

=== domchenko/OldCards/resources/oldcards_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<oldcards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="oldcards.xsd"
  xmlns:authorspace="http://www.example.net/test">
  <oldcard id="ID1">
    <theme>Architecture</theme>
    <type isSent="yes">Simple</type>
    <country>Spain</country>
    <year>1875</year>
    <authors>
      <author>
        <authorspace:name>Antonio</authorspace:name>
        <authorspace:surname>Gaudi</authorspace:surname>
      </author>
    </authors>
    <valuable>Historical</valuable>
  </oldcard>
  
  <oldcard id="ID2">
    <theme>Flowers</theme>
    <type isSent="no">Congratulatory</type>
    <country>Ukraine</country>
    <year>1986</year>
    <authors>
      <author>
        <authorspace:name>Kateryna</authorspace:name>
        <authorspace:surname>Bilokur</authorspace:surname>
      </author>
    </authors>
    <valuable>Collection</valuable>
  </oldcard>
  
  <oldcard id="ID3">
    <theme>Red Book Animals</theme>
    <type isSent="yes">Congratulatory</type>
    <country>Ukraine</country>
    <year>2014</year>
    <valuable>Thematic</valuable>
  </oldcard>
  
  <oldcard id="ID4">
    <theme>Hotels</theme>
    <type isSent="yes">Promotional</type>
    <country>USA</country>
    <year>1911</year>
    <authors>
      <author>
        <authorspace:name>Peter</authorspace:name> 
        <authorspace:surname>Brown</authorspace:surname>
      </author>
      <author>
        <authorspace:name>Elizabeth</authorspace:name>
        <authorspace:surname>Crowdy</authorspace:surname>
      </author>
    </authors>
    <valuable>Historical</valuable>
  </oldcard>
</oldcards>
